### PR TITLE
Added logic to make sure boundary is not returned with HTMLBody.

### PR DESCRIPTION
**Pull request by ibrahimlawal**
Added logic to make sure that boundary does not get added to returned HTMLBody.
Added .gitignore
Ran did PSR-2 check on files

### CODE REVIEW

**Comment by djmattyg007** [comment]
This is very difficult to review because you've mixed in changes to a whole bunch of things. It would be very helpful if you could split this up into two separate pull requests:
1. The logic change
2. The code style and readme changes

A preliminary note is that the two lines you've added to the gitignore file should have leading slashes, as these files will only appear in the top level of the repository.

Also, why is the UTF check removed? This commit appears to be from another person, did you mean to include it?

**Comment by djmattyg007** [comment]
Also, why was the readme converted into a markdown file? It's a plain text file for a reason.

**Comment by ibrahimlawal** [comment]
Hi Matthew,

Thanks for your response. Awesome comment about putting leading slashes before the `.gitignore` lines. I have just learnt that from you.

I didn't mean to include the [Remove UTF Check commit](https://github.com/ibrahimlawal/official-library-php-email-parser/commit/c4763a8148eeb3b255310af5035b29aa73aa04a3) in my commit. Perhaps he did it for his own purposes. His was the most recent fork as at the time I checked the [network](https://github.com/djmattyg007/official-library-php-email-parser/network) so, I forked it.

The logic change I added is in the [PlancakeEmailParser.php](PlancakeEmailParser.php). All possible boundaries are added to the `$boundaries` variable at the time of building the array. Then when checking if each line is a boundary, rather than doing a `substr` call we can compare directly with the boundary stored. This also takes care of the two possible boundaries in a multipart email.

Code style changes were mainly a result of running code sniffer with check PSR-2 option. All code were made to conform to the [PSR-2 guidelines](http://www.php-fig.org/psr/psr-2/). I added codesniffer to the [composer.json](composer.json) require-dev so it could be installed by developers who want to contribute. they'd just `composer install`. Any subsequent contributor can run it by doing:

``` bash
$ ./vendor/bin/phpcbf --standard=PSR2 ./PlancakeEmailParser.php
$ ./vendor/bin/phpcbf --standard=PSR2 ./tests/run_tests.php
```

before making a pull request. Perhaps it should be mentioned in the readme if adopted. This run  affected the [tests/run_tests.php](tests/run_tests.php) and [PlancakeEmailParser.php](PlancakeEmailParser.php)

I don't know the reason it has stayed as txt. Markdown is more legible, so thought to update it.

**Comment by djmattyg007** [comment]
I'm not against the code style updates. I'd just prefer it if they were in a separate pull request, or at the very least in a separate commit to the actual logic changes. This link gives a good overview of why this is important: http://programmers.stackexchange.com/questions/154679/reformatting-and-version-control

I **am** against changing the format of the readme file to markdown. I'm not a fan of markdown, restructured text, or any of their derivatives and variants. I strongly disagree that it is somehow more legible, and generally find the syntax a pain to deal with. Please revert the markdown-related changes to the readme file.

**Comment by djmattyg007** [comment]
I also noticed that the second commit submitted as part of this pull request has a poorly formatted commit message. Commit messages should have a clearly defined subject line and body. This article gives a good overview of what a good commit message should look like: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by ibrahimlawal** [comment]
Closed this request since I have made a new request with both changes included as separate commits.

**Pull request closed without merging**
