### PR TITLE
Modified logic to avoid returning boundary in HTMLBody

### PR DESCRIPTION
**Pull request by ibrahimlawal**
- Modified logic to make sure that boundary does not get added to returned HTMLBody.
- Added .gitignore
- Ran did PSR-2 check on files

### CODE REVIEW

**Comment by djmattyg007** [comment]
Thanks for re-submitting the pull request. I had a couple more notes that I missed the first time around:
- The latest version of the code sniffer library is 2.5.1, so it doesn't make a lot of sense to start off by allowing an out of date version (~2.3)
- The rest of the library uses camelCase, not snake_case, so please rename the `boundaries_raw` variable
- No tests have been added or updated as part of this change. I'd strongly suggest adding at least one test so I know what sort of situation this is catering for.

FInally, please don't use markdown in your commit messages. It looks ugly on both github and (more importantly) on the command line.

**Comment by ibrahimlawal** [comment]
Requested commits added

**Comment by ibrahimlawal** [comment]
Hi Matthew,

I haven't heard from you since my last commits. Hope you're good.

Thanks!

**Comment by djmattyg007** [comment]
Sorry, I've been working late this week. I'll be reviewing this over the weekend.

**Comment by djmattyg007** [comment]
Sorry for the delay. I had actually reviewed this a couple of days ago, but only just now got around to merging it in and pushing it up. Thanks for your contribution!

**Comment by djmattyg007** [comment]
As an FYI, once I merge in this PR, I'll be tagging a new release as v3.0.0.

https://github.com/plancake/official-library-php-email-parser/pull/30

**Comment by ibrahimlawal** [comment]
Awesome. Excellent work.

**Comment by djmattyg007** [comment]
I've just pushed v3.0.0!

**Pull request merged**
